da <- read.csv("./Money/Data/Phillips.csv", stringsAsFactors = FALSE)
head(da)
colnames(da) <- c("Date", "Inflation", "Unemployment")
head(da)
tail(da)
plot(da$Unemployment[1:18], da$Inflation[1:18], xlab = "Unemployment", ylab = "Inflation")
eq1 <- lm(da$Unemployment[1:18] ~ da$Inflation[1:18] + I(da$Inflation[1:18]^2), )
summary(eq1)
lines(da$Unemployment[1:18], eq1$fitted.values, col = 'red')
