da <- read.csv("./Money/Data/Phillips.csv", stringsAsFactors = FALSE)
head(da)
colnames(da) <- c("Date", "Inflation", "Unemployment")
head(da)
tail(da)
plot(da$Unemployment[1:18], da$Inflation[1:18], xlab = "Unemployment", ylab = "Inflation")
eq1 <- lm(da$Inflation[1:18] ~ da$Unemployment[1:18] + I(da$Unemployment[1:18]^2))
summary(eq1)
lines(eq1$fitted.values, col = 'darkgreen')
#------------------------------------------------
da <- read.csv("./Money/Data/USPhillips.csv", stringsAsFactors = FALSE, 
               skip = 23)
colnames(da) <- c("Date", "CPI", "Inflation", "Unemployment")
da$Date <- as.Date(da$Date, format = "%Y-%m-%d")
da$Inflation <- as.numeric(gsub('%', "", da$Inflation))
head(da)
str(da)
plot(da$Unemployment[1:216], da$Inflation[1:216], main = "US Unemployment
     and Inflation (1948-65)", xlab = "Unemployment", ylab = "Inflation")
head(da$Date[1:216])
tail(da$Date[1:216])
eq1 <- lm(da$Inflation[1:216] ~ da$Unemployment[1:216])
summary(eq1)
abline(eq1, col = "darkgreen", lwd = 3)
